feat: add option to run specfic configuration after install

diff --git a/system/bin/chroot-distro b/system/bin/chroot-distro
--- a/system/bin/chroot-distro
+++ b/system/bin/chroot-distro
@@ -192,6 +192,7 @@ safe_mount() {
 #
 #############################################################################
 
+# shellcheck disable=SC2329
 get_distro_info() {
     distro_name="$1"
     info_type="$2" # version, supported_arch, aarch64_url, arm_url
@@ -203,6 +204,18 @@ get_distro_info() {
         "aarch64_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/archlinux-latest-aarch64.tar.xz" ;;
         "arm_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/archlinux-latest-arm.tar.xz" ;;
         esac
+        # distro specfic configuration
+        distro_setup() {
+            # Fix environment variables on login or su.
+            f=""
+            for f in su su-l system-local-login system-remote-login; do
+                echo "session  required  pam_env.so readenv=1" >>./etc/pam.d/"${f}"
+            done
+
+            # Configure en_US.UTF-8 locale.
+            busybox sed -i -E 's/#[[:space:]]?(en_US.UTF-8[[:space:]]+UTF-8)/\1/g' ./etc/locale.gen
+            run_chroot_cmd locale-gen
+        }
         ;;
     "debian")
         case "$info_type" in
@@ -210,6 +223,12 @@ get_distro_info() {
         "aarch64_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/debian-latest-aarch64.tar.xz" ;;
         "arm_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/debian-latest-arm.tar.xz" ;;
         esac
+        # distro specfic configuration
+        distro_setup() {
+            # Configure en_US.UTF-8 locale.
+            sed -i -E 's/#[[:space:]]?(en_US.UTF-8[[:space:]]+UTF-8)/\1/g' ./etc/locale.gen
+            run_chroot_cmd DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
+        }
         ;;
     "fedora")
         case "$info_type" in
@@ -217,6 +236,12 @@ get_distro_info() {
         "aarch64_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/fedora-latest-aarch64.tar.xz" ;;
         "arm_url") busybox echo "" ;; # Not supported
         esac
+        # distro specfic configuration
+        distro_setup() {
+            # Fix environment variables on login or su.
+            run_chroot_cmd authselect opt-out
+            echo "session  required  pam_env.so readenv=1" >>./etc/pam.d/system-auth
+        }
         ;;
     "ubuntu")
         case "$info_type" in
@@ -224,6 +249,12 @@ get_distro_info() {
         "aarch64_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/ubuntu-latest-aarch64.tar.xz" ;;
         "arm_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/ubuntu-latest-arm.tar.xz" ;;
         esac
+        # distro specfic configuration
+        distro_setup() {
+            # Configure en_US.UTF-8 locale.
+            sed -i -E 's/#[[:space:]]?(en_US.UTF-8[[:space:]]+UTF-8)/\1/g' ./etc/locale.gen
+            run_chroot_cmd DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
+        }
         ;;
     "ubuntu-lts")
         case "$info_type" in
@@ -231,6 +262,12 @@ get_distro_info() {
         "aarch64_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/ubuntu-lts-latest-aarch64.tar.xz" ;;
         "arm_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/ubuntu-lts-latest-arm.tar.xz" ;;
         esac
+        # distro specfic configuration
+        distro_setup() {
+            # Configure en_US.UTF-8 locale.
+            sed -i -E 's/#[[:space:]]?(en_US.UTF-8[[:space:]]+UTF-8)/\1/g' ./etc/locale.gen
+            run_chroot_cmd DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
+        }
         ;;
     "kali")
         case "$info_type" in
@@ -238,6 +275,12 @@ get_distro_info() {
         "aarch64_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/kali-latest-aarch64.tar.xz" ;;
         "arm_url") busybox echo "https://github.com/sabamdarif/chroot-distro/releases/download/distro/kali-latest-arm.tar.xz" ;;
         esac
+        # distro specfic configuration
+        distro_setup() {
+            # Configure en_US.UTF-8 locale.
+            sed -i -E 's/#[[:space:]]?(en_US.UTF-8[[:space:]]+UTF-8)/\1/g' ./etc/locale.gen
+            run_chroot_cmd DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
+        }
         ;;
     *)
         busybox echo ""
@@ -340,6 +383,61 @@ check_if_running_as_root() {
         exit 1
     fi
     unset user_id
+}
+
+#############################################################################
+#
+# FUNCTION TO RUN COMMAND IN CHROOT ENVIRONMENT
+#
+# Simplified function to execute commands inside chroot
+# without full login setup.
+#
+#############################################################################
+
+run_chroot_cmd() {
+    if [ -z "${distro_name-}" ]; then
+        msg
+        msg "${BRED}Error: called run_chroot_cmd() but \${distro_name} is not set.${RST}"
+        msg
+        return 1
+    fi
+
+    distro_path="${INSTALLED_ROOTFS_DIR}/${distro_name}"
+
+    # Check if distribution is installed
+    if [ ! -d "$distro_path" ]; then
+        msg
+        msg "${BRED}Error: distribution '${YELLOW}${distro_name}${BRED}' is not installed.${RST}"
+        msg
+        return 1
+    fi
+
+    # Ensure basic mount points exist and are mounted
+    busybox mkdir -p "${distro_path}/dev"
+    busybox mkdir -p "${distro_path}/proc"
+    busybox mkdir -p "${distro_path}/sys"
+
+    # Mount essential filesystems if not already mounted
+    safe_mount "/dev" "${distro_path}/dev"
+    safe_mount "/proc" "${distro_path}/proc"
+    safe_mount "/sys" "${distro_path}/sys"
+
+    # Execute command in chroot
+    chroot "$distro_path" /usr/bin/env -i \
+        "PATH=${DEFAULT_PATH_ENV}" \
+        "LANG=C.UTF-8" \
+        "TERM=${TERM-xterm-256color}" \
+        "TMPDIR=/tmp" \
+        "$@"
+
+    chroot_run_exit_code=$?
+
+    # Unmount filesystems after command execution
+    busybox umount "${distro_path}/sys" 2>/dev/null || true
+    busybox umount "${distro_path}/proc" 2>/dev/null || true
+    busybox umount "${distro_path}/dev" 2>/dev/null || true
+
+    return $chroot_run_exit_code
 }
 
 #############################################################################
@@ -569,7 +667,7 @@ command_install() {
 
     # Write important environment variables to /etc/environment.
     busybox chmod u+rw "${INSTALLED_ROOTFS_DIR:?}/${distro_name:?}/etc/environment" >/dev/null 2>&1 || true
-    busybox msg "${BLUE}[${GREEN}*${BLUE}] ${CYAN}Writing file '${INSTALLED_ROOTFS_DIR:?}/${distro_name:?}/etc/environment'...${RST}"
+    msg "${BLUE}[${GREEN}*${BLUE}] ${CYAN}Writing file '${INSTALLED_ROOTFS_DIR:?}/${distro_name:?}/etc/environment'...${RST}"
     for var in ANDROID_ART_ROOT ANDROID_DATA ANDROID_I18N_ROOT ANDROID_ROOT \
         ANDROID_RUNTIME_ROOT ANDROID_TZDATA_ROOT BOOTCLASSPATH COLORTERM \
         DEX2OATBOOTCLASSPATH EXTERNAL_STORAGE; do
@@ -704,6 +802,19 @@ command_install() {
 
     # Unmount /dev or any other if any
     busybox umount "${INSTALLED_ROOTFS_DIR:?}/${distro_name:?}/dev" 2>/dev/null || true
+
+    # Run optional distro-specific hook.
+    get_distro_info "$distro_name"
+    if type distro_setup >/dev/null 2>&1; then
+        msg "${BLUE}[${GREEN}*${BLUE}] ${CYAN}Running distribution-specific configuration steps...${RST}"
+        (
+            cd "${INSTALLED_ROOTFS_DIR}/${distro_name}" || {
+                msg "${BRED}Error: directory doesn't exist${RST}"
+                exit 1
+            }
+            distro_setup
+        )
+    fi
 
     msg
     msg "${BLUE}[${GREEN}*${BLUE}] ${CYAN}Installation completed successfully!${RST}"
